{
  # "vocab-file": /mnt/ssd-1/data/20B_tokenizer.json,
  "vocab-file": "/mnt/ssd-2/pile/20B_tokenizer.json",
  # "data_path": "/mnt/ssd-1/data/pile_20B_tokenizer/pile_20B_tokenizer_text_document",
  "data_path": "/mnt/ssd-2/pile_deduped/pile_20B_tokenizer_text_document",
  "load": "/mnt/hdd-0/alyssaloo/pythia-v2-160M",
  # "save": "/mnt/ssd-2/lintangsutawika/pythia-v2-160M/",

  # parallelism settings
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,

  "num_layers": 12,
  "hidden_size": 768,
  "num_attention_heads": 12,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",

  "attention_config": [[["flash"], 12]],

  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": true,

  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.0006,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 0.00006,

  "zero_optimization": {
    "stage": 0, #changed from 1
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

  "train_micro_batch_size_per_gpu": 32,
  "gas": 1,
  "data_impl": "mmap",
  "num_workers": 1,

  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  "train-iters": 143000,
  "lr-decay-iters": 143000,
  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.01,
  "checkpoint-factor": 1000,
  # "extra-save-iters": [0,1,2,4,8,16,32,64,128,256,512],
  "eval-interval": 1, # changed from 40000
  "eval-iters": 1, # changed from 10
  "exit_interval": 35010,

  "log_interval": 10,
  "steps_per_print": 10,
  "wall_clock_breakdown": true,

  "tokenizer_type": "HFTokenizer"
}
